Repository django/django, pull requests merged in 2023-12, with the labels that each got.

#17561 Refs #35003 -- Corrected margins in admin for LTR languages.
  django/contrib/admin/static/admin/css/forms.css
Labels: selenium

#17527 Changed the screenshots Github workflow to run in the PR's branch by using pull_request as event trigger.
  .github/workflows/screenshots.yml
Labels: screenshots 🖼️

#17589 Fixed #35012 -- Restored wrapping admin fieldsets with multiple fields per line.
  django/contrib/admin/static/admin/css/forms.css
  docs/releases/4.2.9.txt
  docs/releases/5.0.1.txt
Labels: selenium, screenshots 🖼️

#17603 Removed unnecessary write permission from screenshots workflow.
  .github/workflows/screenshots.yml
Labels: screenshots 🖼️

#17388 Fixed #34909 -- Associated links in admin navigation sidebar with row descriptions.
  django/contrib/admin/templates/admin/app_list.html
  tests/admin_views/test_nav_sidebar.py
  tests/admin_views/tests.py
Labels: DjangoCon 🦄, selenium

#17652 Fixed #35065 -- Corrected border color for autocomplete fields with errors in admin.
  django/contrib/admin/static/admin/css/autocomplete.css
Labels: selenium

#17625 Fixed #34670 -- Improved loading of theme in admin.
  django/contrib/admin/static/admin/js/theme.js
  django/contrib/admin/templates/admin/base.html
Labels: selenium
