Repository django/django, pull requests merged in 2023-10, with the labels that each got.

#17360 Refs #34043 -- Added context managers to SeleniumTestCase for changing window size.
  django/test/selenium.py
  tests/admin_views/tests.py
  tests/admin_widgets/tests.py
Labels: selenium

#17374 Refs #34043 -- Added --screenshots option to runtests.py and selenium tests.
  .gitignore
  django/test/selenium.py
  docs/internals/contributing/writing-code/unit-tests.txt
  docs/releases/5.1.txt
  tests/admin_views/tests.py
  tests/runtests.py
Labels: selenium

#16963 Refs #34043 -- Added GitHub action to capture screenshots in Selenium tests.
  .github/workflows/screenshots.yml
Labels: selenium, screenshots 🖼️

#17380 Fixed permissions for GitHub action with screenshots.
  .github/workflows/screenshots.yml
Labels: screenshots 🖼️

#17378 Made SeleniumTests.test_select_multiple less flaky by improving Selenium waits.
  tests/admin_views/test_autocomplete_view.py
Labels: selenium, screenshots 🖼️

#17382 Fixed #34905 -- Corrected admin's main content element rendered in <main> tag.
  django/contrib/admin/templates/admin/base.html
  tests/admin_views/test_nav_sidebar.py
  tests/admin_views/tests.py
Labels: selenium, screenshots 🖼️

#17385 Fixed #34911 -- Corrected HTML heading levels on admindocs' main page.
  django/contrib/admindocs/templates/admin_doc/index.html
  tests/admin_views/tests.py
Labels: DjangoCon 🦄, selenium

#17386 Fixed #34912 -- Fixed size of back links and bookmarklet help in admindocs pages.
  django/contrib/admindocs/templates/admin_doc/bookmarklets.html
  django/contrib/admindocs/templates/admin_doc/model_detail.html
  django/contrib/admindocs/templates/admin_doc/template_detail.html
  django/contrib/admindocs/templates/admin_doc/view_detail.html
Labels: DjangoCon 🦄, selenium

#17387 Fixed #34913 -- Added borders on high contrast mode in the admin.
  django/contrib/admin/static/admin/css/base.css
  django/contrib/admin/static/admin/css/changelists.css
Labels: DjangoCon 🦄, selenium

#17392 Fixed #27403 -- Doc'd that QuerySet.prefetch_related() doesn't guarantee transactional consistency.
  docs/ref/models/querysets.txt
Labels: DjangoCon 🦄

#17384 Fixed #15578 -- Stated the processing order of fixtures in the fixtures docs.
  docs/topics/db/fixtures.txt
Labels: DjangoCon 🦄

#17406 Doc'd writing integration tests for the system check framework.
  docs/ref/checks.txt
  docs/topics/checks.txt
Labels: DjangoCon 🦄
