Repository django/django, pull requests merged in 2024-05, with the labels that each got.

#18080 Added a high contrast mode to screenshot cases.
  django/test/selenium.py
  docs/internals/contributing/writing-code/unit-tests.txt
  tests/admin_views/tests.py
Labels: selenium, screenshots 🖼️

#18133 Migrated to ESLint 9+.
  .eslintignore
  .eslintrc
  .pre-commit-config.yaml
  django/contrib/admin/static/admin/js/SelectFilter2.js
  django/contrib/admin/static/admin/js/actions.js
  django/contrib/admin/static/admin/js/popup_response.js
  django/contrib/gis/static/gis/js/OLMapWidget.js
  eslint.config.mjs
  js_tests/admin/actions.test.js
  js_tests/admin/navigation.test.js
  package.json
Labels: selenium

#18153 Screenshot workflow improvements [part 1]
  .github/workflows/screenshots.yml
  django/test/selenium.py
Labels: selenium, screenshots 🖼️

#18151 Refs #35404 -- Fixed line height of admin fieldset labels.
  django/contrib/admin/static/admin/css/forms.css
Labels: selenium, screenshots 🖼️

#18149 Improved the screenshots workflow.
  django/test/selenium.py
Labels: selenium, screenshots 🖼️

#18075 Removed fictional class 'extrapretty' from admin docs.
  docs/ref/contrib/admin/index.txt
Labels: reminder

#18181 Refs #35189 -- Moved CSS details' cursor declaration to base.css.
  django/contrib/admin/static/admin/css/base.css
  django/contrib/admin/static/admin/css/changelists.css
Labels: selenium

#18037 Fixed #18119 -- Added a DomainNameValidator validator.
  django/core/validators.py
  docs/ref/validators.txt
  docs/releases/5.1.txt
  tests/validators/tests.py
Labels: Djangonauts :rocket:

#18155 Fixed #35393 -- Added excluded pk as a hidden field to the inline admin.
  django/contrib/admin/helpers.py
  tests/admin_inlines/admin.py
  tests/admin_inlines/models.py
  tests/admin_inlines/tests.py
Labels: selenium

#18187 Fixed #35467 -- Replaced `urlparse` with `urlsplit`.
  django/contrib/admin/options.py
  django/contrib/admin/templatetags/admin_urls.py
  django/contrib/auth/decorators.py
  django/contrib/auth/middleware.py
  django/contrib/auth/mixins.py
  django/contrib/auth/views.py
  django/contrib/staticfiles/handlers.py
  django/forms/fields.py
  django/http/response.py
  django/middleware/common.py
  django/middleware/csrf.py
  django/test/client.py
  django/test/testcases.py
  django/utils/http.py
  docs/ref/urlresolvers.txt
  tests/admin_views/tests.py
  tests/csrf_tests/tests.py
Labels: benchmark
