Repository django/django, pull requests merged in 2024-10, with the labels that each got.

#18552 Fixed #35742 -- Removed hardcoded "username" references in admin templates.
  django/contrib/admin/templates/admin/auth/user/add_form.html
  django/contrib/admin/templates/admin/login.html
  django/contrib/admin/templates/registration/password_reset_email.html
Labels: selenium

#18634 Fixed #35799 -- Fixed positioning of icon in RTL
  django/contrib/admin/static/admin/css/forms.css
  django/contrib/admin/static/admin/js/inlines.js
Labels: DjangoCon 🦄, selenium, screenshots 🖼️

#18656 Fixed #35809 -- Set background color for selected rows in the admin's form select widget.
  django/contrib/admin/static/admin/css/forms.css
  docs/releases/5.1.2.txt
  tests/admin_views/tests.py
Labels: selenium, screenshots 🖼️

#18633 Fixed #35792 -- Updated the _get_group_permissions method of ModelBackend.
  django/contrib/auth/backends.py
Labels: benchmark

#18250 Added short explanation for exception to include() usage in tutorial page 1.
  docs/intro/tutorial01.txt
Labels: DjangoCon Europe 🏰

#18662 [4.2.x] Added GitHub Action workflow to test all Python versions listed in the project config file.
  .github/workflows/python_matrix.yml
Labels: python-matrix

#18652 Fixed #35795 -- Updated "Delete" button semantics and accessibility
  django/contrib/admin/static/admin/js/inlines.js
  django/contrib/admin/templates/admin/actions.html
  django/views/templates/technical_500.html
Labels: selenium, screenshots 🖼️

#18682 Fixed #35731 -- Extend documentation about db_default and DatabaseDefault.
  docs/ref/models/fields.txt
  docs/topics/db/models.txt
Labels: Djangonauts :rocket:

#18704 Updated solutions list on using REMOTE_USER how-to.
  docs/howto/auth-remote-user.txt
Labels: Djangonauts :rocket:

#18710 Improved readability of triage workflow image by increasing its size and color contrast.
  docs/internals/_images/triage_process.svg
  docs/internals/contributing/triaging-tickets.txt
Labels: Djangonauts :rocket:

#18716 Refs #35844 -- Corrected expected error messages in commands tests on Python 3.14+.
  django/utils/version.py
  tests/admin_scripts/tests.py
  tests/user_commands/tests.py
Labels: Djangonauts :rocket:

#18731 Refs #34900 -- Removed usage of deprecated glob.glob1().
  django/core/cache/backends/filebased.py
Labels: Djangonauts :rocket:

#18728 Removed unneeded sentence on contributing page.
  docs/intro/contributing.txt
Labels: Djangonauts :rocket:

#18733 Refs #35844 -- Expanded compatibility for expected error messages in command tests on Python 3.12 and 3.13.
  tests/admin_scripts/tests.py
  tests/user_commands/tests.py
Labels: Djangonauts :rocket:

#18705 Added missing lang attributes to html element in docs.
  docs/intro/overview.txt
  docs/ref/contrib/flatpages.txt
  docs/topics/http/views.txt
Labels: Djangonauts :rocket:

#18707 Fixed #35856 -- Added QuerySet.explain() support for MEMORY/SERIALIZE option on PostgreSQL 17+.
  django/db/backends/postgresql/features.py
  django/db/backends/postgresql/operations.py
  docs/ref/models/querysets.txt
  docs/releases/5.2.txt
  tests/queries/test_explain.py
Labels: Djangonauts :rocket:

#18741 Fixed #35876 -- Displayed non-ASCII fieldset names when rendering ModelAdmin.fieldsets.
  django/contrib/admin/templates/admin/includes/fieldset.html
  docs/releases/5.1.3.txt
  tests/admin_inlines/tests.py
  tests/admin_views/admin.py
  tests/admin_views/tests.py
Labels: selenium
