Repository django/django, pull requests merged in 2024-08, with the labels that each got.

#18344 Fixed #35489 -- Fixed vertical alignment of raw_id_fields widget.
  django/contrib/admin/templates/admin/widgets/foreign_key_raw_id.html
  tests/admin_widgets/tests.py
Labels: selenium, screenshots 🖼️, Djangonauts :rocket:

#18442 Fixed #35553 -- Added a regex to catch import*as.
  django/contrib/staticfiles/storage.py
  tests/staticfiles_tests/project/documents/cached/module.js
  tests/staticfiles_tests/test_storage.py
Labels: Djangonauts :rocket:

#18236 Documented that SessionMiddleware is required for admin.
  docs/ref/contrib/admin/index.txt
Labels: DjangoCon Europe 🏰

#18491 Fixed #35686 -- Added table headers to app list tables for screen readers.
  django/contrib/admin/templates/admin/app_list.html
  tests/admin_changelist/tests.py
  tests/admin_views/tests.py
Labels: selenium, screenshots 🖼️

#18346 Fixed #35083 -- Made method_decorator work with async functions.
  django/utils/decorators.py
  docs/releases/5.2.txt
  tests/decorators/tests.py
Labels: Djangonauts :rocket:

#18526 Fixed #35716 -- Fixed VariableDoesNotExist when rendering admin fieldsets.
  django/contrib/admin/templates/admin/change_form.html
  django/contrib/admin/templates/admin/edit_inline/stacked.html
  django/contrib/admin/templates/admin/includes/fieldset.html
  docs/releases/5.1.1.txt
  tests/admin_inlines/tests.py
Labels: selenium
