Repository django/django, pull requests merged in 2024-06, with the labels that each got.

#18233 Fixed #35503 -- Removed PHP references in tutorial 1.
  docs/intro/tutorial01.txt
Labels: DjangoCon Europe 🏰

#18232 Removed changing the port in the first part of the tutorial.
  docs/intro/tutorial01.txt
Labels: DjangoCon Europe 🏰

#18238 Replacing the old concept of 'patch' by 'pull request' or 'contribution'
  docs/faq/contributing.txt
  docs/howto/windows.txt
  docs/index.txt
  docs/intro/contributing.txt
Labels: DjangoCon Europe 🏰

#18243 Changed the order to highlight the success of the action after starting the development server
  docs/intro/tutorial01.txt
Labels: DjangoCon Europe 🏰

#17897 Fixed #34789 -- Prevented updateRelatedSelectsOptions from adding entries to filter_horizontal chosen box.
  django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js
  django/contrib/admin/widgets.py
  tests/admin_views/test_related_object_lookups.py
  tests/admin_widgets/tests.py
  tests/modeladmin/tests.py
Labels: selenium

#18245 Fixed #35488 -- Added fix for raise unhashable type error for unique unhashable fields.
  django/forms/models.py
  tests/model_formsets/tests.py
Labels: DjangoCon Europe 🏰

#18252 Fixed #34881 -- Error with renaming model referenced twice
  django/db/migrations/operations/models.py
  tests/migrations/test_operations.py
Labels: DjangoCon Europe 🏰

#18237 Fixed #35483 -- Added validation for NUL characters in ModelChoiceField and ModelMultipleChoiceField
  django/forms/models.py
  tests/model_forms/test_modelchoicefield.py
  tests/model_forms/tests.py
Labels: DjangoCon Europe 🏰

#18251 Fixed #35505 -- Added extrabody block to admin/base.html.
  django/contrib/admin/templates/admin/base.html
  docs/ref/contrib/admin/index.txt
  docs/releases/5.2.txt
  tests/admin_views/templates/admin/base_site.html
  tests/admin_views/tests.py
Labels: DjangoCon Europe 🏰, selenium

#18282 Refs #35404 -- Fixed padding of admin fieldset checkbox label.
  django/contrib/admin/static/admin/css/forms.css
Labels: screenshots 🖼️, Djangonauts :rocket:

#18285 Fixed #35461 -- Added detail in django tutorial step 8 so that django…
  docs/intro/tutorial08.txt
Labels: Djangonauts :rocket:

#18306 Fixed #35540: Fixed padding issue on the Admin login form.
  django/contrib/admin/static/admin/css/login.css
  docs/intro/_images/admin01.png
Labels: screenshots 🖼️

#18257 Added link to the discord server inside FAQ.
  docs/faq/help.txt
Labels: DjangoCon Europe 🏰

#18259 Fixed #22712 -- Avoided name shadowing of "all" in findstatic command.
  AUTHORS
  django/contrib/staticfiles/finders.py
  django/contrib/staticfiles/management/commands/findstatic.py
  docs/releases/5.2.txt
  tests/staticfiles_tests/test_finders.py
Labels: DjangoCon Europe 🏰
