Repository django/django, pull requests merged in 2024-09, with the labels that each got.

#18527 Refs #35706 -- Prefixed 'Error:' to titles of admin pages with form errors.
  django/contrib/admin/templates/admin/auth/user/change_password.html
  django/contrib/admin/templates/admin/change_form.html
  django/contrib/admin/templates/admin/change_list.html
  django/contrib/admin/templates/admin/login.html
  django/contrib/admin/templates/registration/password_change_form.html
  django/contrib/admin/templates/registration/password_reset_confirm.html
  django/contrib/admin/templates/registration/password_reset_form.html
  tests/admin_changelist/tests.py
  tests/admin_views/tests.py
  tests/auth_tests/test_templates.py
Labels: selenium

#18533 Refs #35706 -- Replaced template _('...') usages with translate tag.
  django/contrib/admin/templates/admin/auth/user/change_password.html
  django/contrib/admin/templates/admin/change_form.html
  django/contrib/admin/templates/admin/change_list.html
  django/contrib/admin/templates/admin/login.html
  django/contrib/admin/templates/registration/password_change_form.html
  django/contrib/admin/templates/registration/password_reset_confirm.html
  django/contrib/admin/templates/registration/password_reset_form.html
Labels: selenium

#18349 Fixed #32831 – marked flaky tests for retry on assertion failure.
  tests/cache/tests.py
Labels: Djangonauts :rocket:

#18571 Fixed #35747 -- Used default ordering in the admin changelist when the ORDER_VAR param is blank.
  django/contrib/admin/views/main.py
  tests/admin_changelist/tests.py
Labels: selenium

#18575 Fixed #35755 -- Hid help text of hidden fields in admin fieldsets.
  django/contrib/admin/templates/admin/includes/fieldset.html
  tests/admin_inlines/models.py
  tests/admin_inlines/tests.py
Labels: selenium

#18576 Pinned Miniforge in benchmark workflow.
  .github/workflows/benchmark.yml
Labels: benchmark

#18335 Fixed #29522 -- Refactored the Deserializer functions to classes.
  AUTHORS
  django/core/serializers/json.py
  django/core/serializers/jsonl.py
  django/core/serializers/python.py
  django/core/serializers/pyyaml.py
  docs/releases/5.2.txt
  docs/topics/serialization.txt
  tests/serializers/test_deserialization.py
  tests/serializers/test_deserializedobject.py
Labels: benchmark

#18239 Removed path() section from tutorial page 1.
  docs/intro/tutorial01.txt
  docs/ref/urls.txt
Labels: DjangoCon Europe 🏰
