Repository django/django, pull requests merged in 2024-11, with the labels that each got.

#17885 Fixed #26001 -- Fixed non-string field exact lookups in ModelAdmin.search_fields.
  django/contrib/admin/options.py
  tests/admin_changelist/admin.py
  tests/admin_changelist/tests.py
Labels: selenium

#18765 Refs #26001 -- Handled relationship exact lookups in ModelAdmin.search_fields.
  django/contrib/admin/options.py
  tests/admin_changelist/admin.py
  tests/admin_changelist/tests.py
Labels: selenium

#18763 Updated instruction sentence on how to claim a ticket.
  docs/internals/contributing/writing-code/submitting-patches.txt
Labels: Djangonauts :rocket:

#18770 Refs #23968 -- Removed unnecessary list comprehension in contrib.admin.helpers.
  django/contrib/admin/helpers.py
Labels: selenium

#18800 Replaced message suggestions from IRC to Discord in contributing docs.
  docs/faq/contributing.txt
  docs/internals/contributing/index.txt
  docs/internals/contributing/new-contributors.txt
Labels: Djangonauts :rocket:

#18772 Removed misleading list of tested OS in GEOS API docs.
  docs/ref/contrib/gis/geos.txt
Labels: Djangonauts :rocket:

#18742 Fixed #34619 -- Ensured FilteredSelectMultiple elements were associated with their labels.
  django/contrib/admin/static/admin/css/responsive.css
  django/contrib/admin/static/admin/css/rtl.css
  django/contrib/admin/static/admin/css/widgets.css
  django/contrib/admin/static/admin/js/SelectFilter2.js
  js_tests/admin/SelectFilter2.test.js
  tests/admin_inlines/tests.py
  tests/admin_views/test_related_object_lookups.py
  tests/admin_views/tests.py
  tests/admin_widgets/tests.py
Labels: selenium, screenshots 🖼️

#18816 Fixed #35791 -- Updated icon button dimensions to ensure size of 24x24 pixels
  django/contrib/admin/static/admin/css/dark_mode.css
  django/contrib/admin/static/admin/css/responsive.css
  django/contrib/admin/static/admin/css/responsive_rtl.css
  django/contrib/admin/static/admin/css/rtl.css
  django/contrib/admin/static/admin/css/widgets.css
  django/contrib/admin/static/admin/img/inline-delete.svg
  django/contrib/admin/templates/admin/base.html
  django/contrib/admin/templates/admin/widgets/related_widget_wrapper.html
  tests/admin_views/test_related_object_lookups.py
  tests/admin_widgets/tests.py
Labels: selenium, screenshots 🖼️, Djangonauts :rocket:

#18056 Fixed #373 -- Added CompositePrimaryKey.
  django/contrib/admin/sites.py
  django/core/serializers/python.py
  django/db/backends/base/schema.py
  django/db/backends/oracle/schema.py
  django/db/backends/sqlite3/schema.py
  django/db/models/__init__.py
  django/db/models/aggregates.py
  django/db/models/base.py
  django/db/models/fields/__init__.py
  django/db/models/fields/composite.py
  django/db/models/fields/related.py
  django/db/models/fields/related_lookups.py
  django/db/models/fields/tuple_lookups.py
  django/db/models/options.py
  django/db/models/query.py
  django/db/models/sql/compiler.py
  django/db/models/sql/query.py
  docs/ref/checks.txt
  docs/ref/models/fields.txt
  docs/releases/5.2.txt
  docs/topics/composite-primary-key.txt
  docs/topics/index.txt
  tests/admin_registration/models.py
  tests/admin_registration/tests.py
  tests/composite_pk/__init__.py
  tests/composite_pk/fixtures/tenant.json
  tests/composite_pk/models/__init__.py
  tests/composite_pk/models/tenant.py
  tests/composite_pk/test_aggregate.py
  tests/composite_pk/test_checks.py
  tests/composite_pk/test_create.py
  tests/composite_pk/test_delete.py
  tests/composite_pk/test_filter.py
  tests/composite_pk/test_get.py
  tests/composite_pk/test_models.py
  tests/composite_pk/test_names_to_path.py
  tests/composite_pk/test_update.py
  tests/composite_pk/test_values.py
  tests/composite_pk/tests.py
  tests/migrations/test_autodetector.py
  tests/migrations/test_operations.py
  tests/migrations/test_state.py
  tests/migrations/test_writer.py
Labels: benchmark

#18837 Fixed #35925 -- FilteredSelectMultiple filter icon missing padding in RTL
  django/contrib/admin/static/admin/css/responsive.css
  django/contrib/admin/static/admin/css/responsive_rtl.css
  django/contrib/admin/static/admin/css/widgets.css
Labels: screenshots 🖼️
