Repository django/django, pull requests merged in 2024-07, with the labels that each got.

#18324 Fixed #23790: Added warning to AppConfig.label docs reference.
  AUTHORS
  docs/ref/applications.txt
Labels: Djangonauts :rocket:

#18298 Fixed #35511 -- Documentation uses the py binary in Windows, which may not always be available
  docs/howto/windows.txt
Labels: Djangonauts :rocket:

#18268 Fixed #35520 -- Used correct database for `ModelAdmin` transactions
  django/contrib/admin/options.py
  django/contrib/auth/admin.py
  tests/admin_views/test_multidb.py
  tests/admin_views/tests.py
  tests/auth_tests/test_admin_multidb.py
Labels: selenium

#18264 Replaced "patch" with "contribution" on submitting patches page.
  docs/internals/contributing/localizing.txt
  docs/internals/contributing/triaging-tickets.txt
  docs/internals/contributing/writing-code/submitting-patches.txt
Labels: DjangoCon Europe 🏰

#18240 Fixed 35506 -- Clarified confusing 'URLconf' references in tutorial 1.
  docs/intro/tutorial01.txt
Labels: DjangoCon Europe 🏰

#18367 Removed duplicate inline from tests.admin_inlines.admin.PhotographerAdmin.
  tests/admin_inlines/admin.py
Labels: selenium

#18352 Fixed #35541 -- Fixed paginator border in admin CSS.
  django/contrib/admin/static/admin/css/base.css
  docs/intro/_images/admin04t.png
  docs/intro/_images/admin06t.png
  docs/intro/_images/admin12t.png
Labels: screenshots 🖼️

#18026 Fixed #35331 -- Updated dropdown lists with new entries added via the "+" sign from M2M field.
  django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js
  tests/admin_views/test_related_object_lookups.py
Labels: selenium

#18341 Fixed #35546 -- Updated contributing pages to align with current requirement of having an accepted ticket
  docs/internals/contributing/bugs-and-features.txt
  docs/internals/contributing/writing-code/submitting-patches.txt
Labels: Djangonauts :rocket:
