Repository django/django, pull requests merged in 2024-02, with the labels that each got.

#17839 Fixed #35171 -- Updated the design of the "Congrats" page.
  django/views/templates/default_urlconf.html
Labels: selenium

#17854 Fixed #35195 -- Removed unnecessary type="text/css" attributes from <style> tags.
  django/contrib/admindocs/templates/admin_doc/model_detail.html
  django/views/templates/csrf_403.html
  django/views/templates/technical_404.html
  django/views/templates/technical_500.html
Labels: selenium

#17814 Fixed #33037 -- Fixed Trunc() with offset timezones on MySQL, SQLite, Oracle.
  AUTHORS
  django/db/backends/sqlite3/_functions.py
  django/db/backends/utils.py
  tests/db_functions/datetime/test_extract_trunc.py
Labels: Djangonauts :rocket:

#17811 Fixed #29725 -- Removed unnecessary join in QuerySet.count() and exists() on a many to many relation.
  django/db/models/fields/related_descriptors.py
  tests/many_to_many/models.py
  tests/many_to_many/tests.py
Labels: Djangonauts :rocket:

#17868 Used <span> instead of <div> in admin theme button.
  django/contrib/admin/templates/admin/color_theme_toggle.html
Labels: selenium

#16942 Fixed #34429 -- Allowed setting unusable passwords for users in the auth forms.
  AUTHORS
  django/contrib/admin/static/admin/css/unusable_password_field.css
  django/contrib/admin/static/admin/js/unusable_password_field.js
  django/contrib/admin/templates/admin/auth/user/add_form.html
  django/contrib/admin/templates/admin/auth/user/change_password.html
  django/contrib/auth/admin.py
  django/contrib/auth/forms.py
  docs/releases/5.1.txt
  docs/topics/auth/default.txt
  tests/admin_views/test_password_form.py
  tests/auth_tests/test_forms.py
  tests/auth_tests/test_views.py
Labels: selenium

#17894 Fixed #35140 -- Increased font size in debug views.
  django/views/templates/csrf_403.html
  django/views/templates/technical_404.html
  django/views/templates/technical_500.html
Labels: selenium, Djangonauts :rocket:

#17901 Fixed #35246 -- Made Field.unique a cached property.
  django/db/models/fields/__init__.py
Labels: benchmark

#17880 Fixed #35198 -- Fixed facet filters crash on querysets with no primary key.
  django/contrib/admin/filters.py
  docs/releases/5.0.3.txt
  tests/admin_filters/tests.py
Labels: Djangonauts :rocket:
