Repository django/django, pull requests merged in 2025-03, with the labels that each got.

#19216 Applied Black's 2025 stable style.
  django/contrib/gis/db/backends/oracle/models.py
  django/contrib/gis/db/backends/oracle/operations.py
  django/contrib/gis/db/backends/postgis/adapter.py
  django/contrib/gis/db/backends/postgis/models.py
  django/contrib/gis/db/backends/spatialite/models.py
  django/contrib/gis/gdal/__init__.py
  django/contrib/gis/gdal/datasource.py
  django/contrib/gis/gdal/envelope.py
  django/contrib/gis/gdal/error.py
  django/contrib/gis/gdal/geometries.py
  django/contrib/gis/gdal/prototypes/ds.py
  django/contrib/gis/gdal/prototypes/errcheck.py
  django/contrib/gis/gdal/prototypes/generation.py
  django/contrib/gis/gdal/srs.py
  django/contrib/gis/geos/collections.py
  django/contrib/gis/geos/coordseq.py
  django/contrib/gis/geos/error.py
  django/contrib/gis/geos/geometry.py
  django/contrib/gis/geos/libgeos.py
  django/contrib/gis/geos/prototypes/__init__.py
  django/contrib/gis/geos/prototypes/coordseq.py
  django/contrib/gis/geos/prototypes/errcheck.py
  django/contrib/gis/geos/prototypes/geom.py
  django/contrib/gis/geos/prototypes/misc.py
  django/contrib/gis/geos/prototypes/predicates.py
  django/contrib/gis/geos/prototypes/topology.py
  django/contrib/gis/utils/__init__.py
  django/contrib/gis/utils/layermapping.py
  django/core/cache/backends/base.py
  django/core/cache/backends/db.py
  django/core/cache/backends/filebased.py
  django/core/cache/backends/locmem.py
  django/forms/forms.py
  django/template/context.py
  tests/admin_views/models.py
  tests/admin_views/tests.py
  tests/auth_tests/test_validators.py
  tests/backends/tests.py
  tests/forms_tests/tests/test_utils.py
  tests/gis_tests/distapp/models.py
  tests/model_fields/test_binaryfield.py
  tests/postgres_tests/test_constraints.py
  tests/serializers/test_data.py
  tests/serializers/test_xml.py
  tests/utils_tests/test_text.py
Labels: no ticket

#19215 Added some heading labels to docs/topics/cache.txt.
  docs/topics/cache.txt
Labels: no ticket

#19214 Fixed #36217 -- Used LogEntry.save() for single object deletion in admin.
  django/contrib/admin/models.py
  django/contrib/admin/options.py
  docs/releases/5.1.7.txt
  docs/releases/5.1.txt
  tests/admin_changelist/tests.py
  tests/admin_utils/test_logentry.py
  tests/admin_views/test_history_view.py
  tests/admin_views/tests.py
Labels: selenium

#19225 Fixed typo in django/db/backends/postgresql/psycopg_any.py comment.
  django/db/backends/postgresql/psycopg_any.py
Labels: no ticket

#19227 Fixed typo in docs/ref/checks.txt.
  docs/ref/checks.txt
Labels: no ticket

#19221 Fixed typo in django/core/cache/backends/redis.py comment.
  django/core/cache/backends/redis.py
Labels: no ticket

#19238 Corrected test case in ExclusionConstraintTests.test_invalid_expressions().
  tests/postgres_tests/test_constraints.py
Labels: no ticket

#19246 Used _expression_refs_exclude() hook in CheckConstraint/UniqueConstraint.validate().
  django/db/models/constraints.py
Labels: no ticket

#19213 Fixed #35816 -- Handled parsing of scientific notation in DTL.
  django/template/base.py
  tests/template_tests/test_parser.py
Labels: benchmark, selenium, Djangonauts :rocket:

#19253 Removed duplicate entries in docs/releases/5.2.txt.
  docs/releases/5.2.txt
Labels: no ticket

#19237 Corrected aggregation example in docs/ref/models/querysets.txt.
  docs/ref/models/querysets.txt
Labels: no ticket

#19279 Made GitHub apply Django template syntax highlighting to HTML files.
  .gitattributes
Labels: no ticket

#19288 Added post pre-release tasks to release docs.
  docs/internals/howto-release-django.txt
Labels: no ticket

#19291 Fixed typo in docs/topics/signals.txt.
  docs/topics/signals.txt
Labels: no ticket

#19299 Updated ogrinfo output in GIS tutorial.
  docs/ref/contrib/gis/tutorial.txt
Labels: no ticket

#18958 Fixed #34917 -- Underlined the 'a' tags in the main content area of the admin.
  django/contrib/admin/static/admin/css/base.css
  django/contrib/admin/static/admin/js/admin/DateTimeShortcuts.js
  django/contrib/admin/static/admin/js/calendar.js
  django/contrib/admin/templates/admin/change_form_object_tools.html
  django/contrib/admin/templates/admin/change_list_object_tools.html
  django/contrib/admin/templates/admin/change_list_results.html
  django/contrib/admin/templates/admin/delete_confirmation.html
  django/contrib/admin/templates/admin/delete_selected_confirmation.html
  django/contrib/admin/templates/admin/index.html
  django/contrib/admin/templates/admin/object_history.html
  django/contrib/admin/templates/admin/submit_line.html
  django/contrib/admin/templatetags/admin_list.py
  django/contrib/auth/templates/auth/widgets/read_only_password_hash.html
  docs/intro/_images/admin04t.png
  docs/intro/_images/admin12t.png
  docs/intro/_images/admin13t.png
  docs/ref/contrib/admin/_images/actions-as-modeladmin-methods.png
  docs/ref/contrib/admin/_images/adding-actions-to-the-modeladmin.png
  docs/ref/contrib/admin/_images/admin-actions.png
  docs/ref/contrib/admin/_images/list_filter.png
  tests/admin_inlines/tests.py
  tests/admin_views/tests.py
  tests/auth_tests/test_forms.py
  tests/auth_tests/test_views.py
Labels: selenium, screenshots 🖼️

#19297 Doc'd how to use Intersphinx in the reusable apps tutorial.
  docs/intro/reusable-apps.txt
Labels: no ticket

#19313 Refs #34619 -- Fixed labels width in FilteredSelectMultiple in the admin.
  django/contrib/admin/static/admin/css/widgets.css
Labels: screenshots 🖼️

#19319 Fixed warnings per flake8 7.2.0.
  django/contrib/gis/db/models/fields.py
  django/db/backends/base/base.py
  django/utils/autoreload.py
  django/utils/translation/trans_real.py
  tests/asgi/tests.py
Labels: no ticket

#19316 Refs #36055 -- Prevented overlap of object-tools buttons and page header in the admin on small screens.
  django/contrib/admin/static/admin/css/responsive.css
Labels: screenshots 🖼️

#19323 Clarified pre_delete and post_delete's origin attributes.
  docs/ref/signals.txt
Labels: no ticket
