Repository django/django, pull requests merged in 2025-01, with the labels that each got.

#17520 Fixed #32819 -- Established relationship between form fields and their errors.
  django/forms/boundfield.py
  docs/ref/forms/api.txt
  docs/releases/5.2.txt
  tests/forms_tests/tests/test_forms.py
Labels: selenium

#19002 Fixed #36063 -- Made a FileField navigate to the object admin change page when in list_display_links.
  django/contrib/admin/templatetags/admin_list.py
  django/contrib/admin/utils.py
  tests/admin_changelist/admin.py
  tests/admin_changelist/models.py
  tests/admin_changelist/tests.py
Labels: selenium

#18857 Fixed #35940 -- Disabled SelectFilter add/remove buttons when appropriate.
  django/contrib/admin/static/admin/css/responsive.css
  django/contrib/admin/static/admin/css/responsive_rtl.css
  django/contrib/admin/static/admin/css/rtl.css
  django/contrib/admin/static/admin/css/widgets.css
  django/contrib/admin/static/admin/js/SelectFilter2.js
  django/contrib/admin/tests.py
  tests/admin_widgets/tests.py
Labels: selenium, screenshots 🖼️

#18972 Fixed #36032 -- Add a link to the URLField value on the app index page.
  django/contrib/admin/utils.py
  docs/releases/5.2.txt
  tests/admin_changelist/admin.py
  tests/admin_changelist/models.py
  tests/admin_changelist/tests.py
  tests/admin_utils/tests.py
Labels: selenium

#18665 Fixed #35998 -- Added caching to django.utils.html.urlize().
  django/utils/html.py
  tests/template_tests/filter_tests/test_urlize.py
Labels: benchmark

#19055 [4.2.x] Refs #36098 -- Fixed validate_ipv4_address() crash for non-string values.
  django/core/validators.py
Labels: python-matrix

#18959 Fixed #36017 -- Used EmailValidator in urlize to detect emails.
  django/utils/html.py
  tests/utils_tests/test_html.py
Labels: benchmark

#19078 Fixed #36114 -- Fixed link visibility when list_display_links field contains only whitespace.
  django/contrib/admin/templatetags/admin_list.py
  tests/admin_changelist/tests.py
Labels: selenium

#18983 Fixed field_defaults test failures due to year-end boundary conditions.
  tests/field_defaults/tests.py
Labels: no ticket

#19102 Prevented docutils from logging to the console in admindocs test
  tests/admin_docs/test_views.py
Labels: no ticket

#19083 Updated the release process documentation to reflect the current process.
  docs/internals/release-process.txt
Labels: no ticket

#19111 Clarified the Releaser's discretion for determining and postponing the release date.
  docs/internals/howto-release-django.txt
Labels: no ticket

#19112 Pinned isort version to "<6.0.0" to avoid undesired reformat.
  .github/workflows/linters.yml
Labels: no ticket

#19081 Fixed #36121 -- Allowed customizing the admin site password change form.
  django/contrib/admin/sites.py
  docs/ref/contrib/admin/index.txt
  docs/releases/6.0.txt
  tests/admin_views/customadmin.py
  tests/admin_views/forms.py
  tests/admin_views/tests.py
Labels: selenium

#17890 Fixed #35235 -- ArrayAgg() doesn't return default when filter contains __in=[].
  django/db/models/expressions.py
  tests/expressions/tests.py
  tests/postgres_tests/test_aggregates.py
Labels: benchmark

#19126 Tweaked docs to avoid reformatting given new black version.
  docs/ref/contrib/postgres/aggregates.txt
  docs/releases/1.10.txt
Labels: no ticket
