Repository django/django, pull requests merged in 2025-04, with the labels that each got.

#19324 Fixed #36283 -- Reverted "Fixed #35798, Refs #31641 -- Prevented admin navigation sidebar loading flicker."
  django/contrib/admin/templates/admin/base.html
  django/contrib/admin/templates/admin/nav_sidebar.html
Labels: selenium

#19326 Fixed typo in django/db/models/options.py.
  django/db/models/options.py
Labels: no ticket

#19331 Fixed #36290 -- Made TupleIn() lookup discard tuples containing None.
  django/db/models/fields/tuple_lookups.py
  docs/releases/5.2.1.txt
  tests/composite_pk/test_filter.py
  tests/foreign_object/models/person.py
  tests/foreign_object/tests.py
Labels: bug

#19341 Fixed #36255 -- Improved accessibility of the admin action button.
  django/contrib/admin/templates/admin/actions.html
  docs/intro/_images/admin04t.png
  docs/intro/_images/admin12t.png
  docs/intro/_images/admin13t.png
  docs/ref/contrib/admin/_images/actions-as-modeladmin-methods.png
  docs/ref/contrib/admin/_images/adding-actions-to-the-modeladmin.png
  docs/ref/contrib/admin/_images/admin-actions.png
  docs/ref/contrib/admin/_images/list_filter.png
  tests/admin_views/templates/admin/admin_views/article/actions.html
Labels: selenium, screenshots 🖼️

#19347 Added supports_expression_defaults check in DefaultTests.test_full_clean() test.
  tests/field_defaults/tests.py
Labels: no ticket

#19198 Disambiguated url in flatpages URLconf example.
  docs/ref/contrib/flatpages.txt
Labels: no ticket

#19365 Sorted imports in django/templatetags/tz.py per isort.
  django/templatetags/tz.py
Labels: no ticket

#19373 Bumped versions in pre-commit and npm configurations.
  .pre-commit-config.yaml
  package.json
Labels: no ticket

#19387 Disabled Google password manager pop-up interfering with selenium tests.
  django/test/selenium.py
Labels: selenium, no ticket

#19389 Fixed #36331 -- Reverted "Fixed #36055 -- Prevented overlap of object-tools buttons and page header in the admin."
  django/contrib/admin/static/admin/css/base.css
  django/contrib/admin/static/admin/css/responsive.css
  django/contrib/admin/templates/admin/base.html
  django/contrib/admin/templates/admin/change_form.html
  django/contrib/admin/templates/admin/change_list.html
  docs/releases/5.2.1.txt
  tests/admin_views/tests.py
Labels: selenium, screenshots 🖼️

#19388 Simplified UserManager.with_perm() by using get_backends().
  django/contrib/auth/models.py
Labels: no ticket

#19376 Skipped label PR job when not running from django/django.
  .github/workflows/labels.yml
Labels: no ticket

#19422 Fixed aggregation tests crash on databases that don't support JSONFields.
  tests/aggregation/models.py
Labels: no ticket

#19398 Fixed #36312 -- Solved `dark_mode.css` size units for svg in Safari
  django/contrib/admin/templates/admin/base.html
Labels: selenium, screenshots 🖼️

#19421 Fixed #36354 -- Removed javascript fallback for outdated browsers not supporting `:has()`.
  django/contrib/admin/static/admin/js/unusable_password_field.js
  django/contrib/admin/templates/admin/auth/user/add_form.html
  django/contrib/admin/templates/admin/auth/user/change_password.html
Labels: DjangoCon Europe 🏰, selenium

#19435 Made cosmetic edits and added upcoming security release to release notes.
  docs/releases/4.2.21.txt
  docs/releases/5.1.9.txt
  docs/releases/5.2.1.txt
Labels: no ticket
