Repository django/django, pull requests merged in 2025-07, with the labels that each got.

#19591 Fixed #36479: Failing test for black formatter missing install simulation on a macOS
  tests/user_commands/tests.py
Labels: python-matrix

#19615 Fixed AttributeError for enterContext() on Python < 3.11.
  tests/composite_pk/test_filter.py
Labels: python-matrix

#19628 Updated asgiref dependency.
  docs/internals/contributing/writing-code/unit-tests.txt
  docs/releases/6.0.txt
  pyproject.toml
  tests/requirements/py3.txt
Labels: no ticket

#19635 Added Django ecosystem page to the documentation.
  docs/faq/general.txt
  docs/internals/contributing/index.txt
  docs/intro/whatsnext.txt
Labels: no ticket

#19493 Skipped test_no_logs_without_debug test when the runner is invoked with --debug-sql.
  tests/backends/base/test_base.py
Labels: no ticket

#19621 Added tests for assertRedirects() when following a redirect.
  tests/test_client_regress/tests.py
Labels: no ticket

#19644 Triggered window resize to fix layout issues.
  django/contrib/admin/tests.py
  tests/admin_views/tests.py
  tests/admin_widgets/tests.py
Labels: selenium, screenshots 🖼️, no ticket

#19662 Fixed incorrectly concatenated string in SimpleBlockTagTests.test_simple_block_tag_with_context_missing_content().
  tests/template_tests/test_custom.py
Labels: no ticket

#19658 Fixed #36516, Refs #36366 -- Fixed changelist footer layout with list_editable and list_filter.
  django/contrib/admin/static/admin/css/changelists.css
  tests/admin_views/tests.py
Labels: selenium, screenshots 🖼️

#19672 Fixed typo in docs/topics/email.txt.
  docs/topics/email.txt
Labels: no ticket

#19684 Fixed writer_name deprecation warning in docutils 0.22+.
  django/contrib/admindocs/utils.py
Labels: no ticket

#19671 Fixed #36055 -- Prevented overlap of object-tools buttons and page header in the admin.
  django/contrib/admin/static/admin/css/base.css
  django/contrib/admin/static/admin/css/responsive.css
  django/contrib/admin/static/admin/css/responsive_rtl.css
  django/contrib/admin/static/admin/css/rtl.css
  docs/intro/_images/admin04t.png
  docs/intro/_images/admin05t.png
  docs/intro/_images/admin12t.png
  docs/intro/_images/admin13t.png
  docs/ref/contrib/admin/_images/actions-as-modeladmin-methods.png
  docs/ref/contrib/admin/_images/adding-actions-to-the-modeladmin.png
  docs/ref/contrib/admin/_images/list_filter.png
  tests/admin_views/models.py
  tests/admin_views/tests.py
Labels: selenium, screenshots 🖼️

#19659 Fixed #36511 -- Ensured filters came before table in keyboard navigation in admin changelist.
  django/contrib/admin/static/admin/css/changelists.css
  django/contrib/admin/static/admin/css/responsive.css
  django/contrib/admin/templates/admin/change_list.html
  tests/admin_views/admin.py
  tests/admin_views/test_skip_link_to_content.py
Labels: selenium, screenshots 🖼️
