Repository django/django, pull requests merged in 2025-02, with the labels that each got.

#19128 Bumped versions in pre-commit and npm configurations.
  .pre-commit-config.yaml
  package.json
  tests/requirements/py3.txt
Labels: no ticket

#19119 Fixed #36140 -- Allowed BaseUserCreationForm to define non required password fields.
  django/contrib/auth/forms.py
  docs/releases/5.1.6.txt
  tests/auth_tests/test_forms.py
Labels: selenium

#19032 Fixed #36055 -- Prevented overlap of object-tools buttons and page header in the admin.
  django/contrib/admin/static/admin/css/base.css
  django/contrib/admin/templates/admin/base.html
  django/contrib/admin/templates/admin/change_form.html
  django/contrib/admin/templates/admin/change_list.html
  tests/admin_views/tests.py
Labels: selenium, screenshots 🖼️

#19010 Fixed #36069 -- Fixed the positioning of the delete button in TabularInlines.
  django/contrib/admin/templates/admin/edit_inline/tabular.html
  tests/admin_inlines/tests.py
Labels: selenium, screenshots 🖼️

#19114 Clarified docs for default email value in UserManager.create_user().
  docs/ref/contrib/auth.txt
Labels: no ticket

#19154 Used "django" repository in twine call in release how-to.
  docs/internals/howto-release-django.txt
Labels: no ticket

#19171 Corrected SHORT_DATE_FORMAT for Korean (ko).
  django/conf/locale/ko/formats.py
Labels: no ticket

#19175 Fixed typo in docs/ref/databases.txt.
  docs/ref/databases.txt
Labels: no ticket

#19164 Corrected wording in docs/ref/models/constraints.txt.
  docs/ref/models/constraints.txt
Labels: no ticket

#19192 Fixed docs build on Sphinx 8.2+.
  docs/conf.py
Labels: no ticket

#19195 Clarified admonition in GeneratedField docs.
  docs/ref/models/fields.txt
Labels: no ticket

#19209 Removed outdated docstring in tests/basic/models.py.
  tests/basic/models.py
Labels: no ticket
