Repository django/django, pull requests merged in 2025-05, with the labels that each got.

#19443 Simplified artifact building steps in docs/internals/howto-release-django.txt.
  docs/internals/howto-release-django.txt
Labels: no ticket

#19446 Cleaned up CVE-2025-32873 security archive description.
  docs/releases/security.txt
Labels: no ticket

#19451 Removed hardcoded pks in admin selenium tests.
  tests/admin_views/tests.py
  tests/admin_widgets/tests.py
Labels: selenium, no ticket

#18270 Fixed #35518 -- Used simpler string operations for converter-less routes
  django/urls/resolvers.py
  tests/urlpatterns/test_resolvers.py
Labels: benchmark

#19428 Update contributing docs for new feature ideas
  docs/internals/contributing/bugs-and-features.txt
  docs/internals/contributing/index.txt
  docs/internals/contributing/triaging-tickets.txt
  docs/internals/contributing/writing-code/submitting-patches.txt
  docs/intro/contributing.txt
Labels: no ticket

#19379 Fixed #35507 -- Improved accessibility using a search landmark and aria-labelledby.
  django/contrib/admin/templates/admin/change_list.html
  django/contrib/admin/templates/admin/search_form.html
  tests/admin_changelist/tests.py
  tests/admin_views/tests.py
Labels: DjangoCon Europe 🏰, selenium, screenshots 🖼️

#18914 Fixed #35829 -- Updated admin icons using Font Awesome Free version 6.7.2.
  django/contrib/admin/static/admin/img/LICENSE
  django/contrib/admin/static/admin/img/README.md
  django/contrib/admin/static/admin/img/README.txt
  django/contrib/admin/static/admin/img/calendar-icons.svg
  django/contrib/admin/static/admin/img/icon-addlink.svg
  django/contrib/admin/static/admin/img/icon-alert.svg
  django/contrib/admin/static/admin/img/icon-calendar.svg
  django/contrib/admin/static/admin/img/icon-changelink.svg
  django/contrib/admin/static/admin/img/icon-clock.svg
  django/contrib/admin/static/admin/img/icon-deletelink.svg
  django/contrib/admin/static/admin/img/icon-hidelink.svg
  django/contrib/admin/static/admin/img/icon-no.svg
  django/contrib/admin/static/admin/img/icon-unknown-alt.svg
  django/contrib/admin/static/admin/img/icon-unknown.svg
  django/contrib/admin/static/admin/img/icon-viewlink.svg
  django/contrib/admin/static/admin/img/icon-yes.svg
  django/contrib/admin/static/admin/img/inline-delete.svg
  django/contrib/admin/static/admin/img/search.svg
  django/contrib/admin/static/admin/img/selector-icons.svg
  django/contrib/admin/static/admin/img/sorting-icons.svg
  django/contrib/admin/static/admin/img/tooltag-add.svg
  django/contrib/admin/static/admin/img/tooltag-arrowright.svg
  docs/releases/6.0.txt
Labels: screenshots 🖼️

#19467 Fixed incorrect spacing in docs/ref/contrib/postgres/fields.txt.
  docs/ref/contrib/postgres/fields.txt
Labels: no ticket

#19450 Refs #34488 -- Fixed file path for ClearableFileInput selenium tests.
  tests/admin_widgets/tests.py
Labels: selenium

#19481 Fixed typo in release notes for 6.0.
  docs/releases/6.0.txt
Labels: no ticket

#19496 Fixed typo in form rendering API docs.
  docs/ref/forms/renderers.txt
Labels: no ticket
