Repository django/django, pull requests merged in 2025-08, with the labels that each got.

#19695 Corrected assertNumQueries() example in docs/topics/testing/tools.txt.
  docs/topics/testing/tools.txt
Labels: no ticket

#19694 [5.1.x] Refs #36535 -- Doc'd that docutils < 0.22 is required.
  docs/internals/contributing/writing-code/unit-tests.txt
  docs/ref/contrib/admin/admindocs.txt
  tests/requirements/py3.txt
Labels: python-matrix

#19711 Fixed typo in django/contrib/gis/geos/geometry.py.
  django/contrib/gis/geos/geometry.py
Labels: no ticket

#19714 Improved docs.yml GitHub Action covering docs quality checks.
  .github/workflows/docs.yml
Labels: no ticket

#19717 Remove unused OneToOneField from DatabaseWrapper.data_types
  django/db/backends/mysql/base.py
  django/db/backends/oracle/base.py
  django/db/backends/postgresql/base.py
  django/db/backends/sqlite3/base.py
Labels: no ticket

#19722 Aligned format of constraint examples in docs/ref/models/constraints.txt.
  docs/ref/models/constraints.txt
Labels: no ticket

#19738 Refs #36528 -- Fixed link underline typo in CSS.
  django/contrib/admin/static/admin/css/base.css
Labels: selenium

#19751 Fixed spelling of "logged-in" when used as an adjective in docs.
  docs/ref/clickjacking.txt
  docs/topics/cache.txt
  docs/topics/security.txt
Labels: no ticket

#19724 Fixed #36382 -- Confirmed support for GDAL 3.11.
  django/contrib/gis/gdal/datasource.py
  django/contrib/gis/gdal/driver.py
  django/contrib/gis/gdal/libgdal.py
  docs/ref/contrib/gis/install/geolibs.txt
  tests/gis_tests/gdal_tests/test_driver.py
Labels: geodjango

#19759 Refs #36366 -- Fixed admin pagination mobile layout.
  django/contrib/admin/static/admin/css/base.css
  django/contrib/admin/static/admin/css/changelists.css
  tests/admin_views/tests.py
Labels: selenium, screenshots 🖼️

#19732 Fixed incorrect use of "generated field" in django/forms/models.py.
  django/forms/models.py
Labels: no ticket

#19733 Fixed #36556 -- Fixed TabularInline width overflowing the page.
  django/contrib/admin/static/admin/css/forms.css
  django/contrib/admin/templates/admin/edit_inline/tabular.html
  tests/admin_inlines/tests.py
Labels: selenium, screenshots 🖼️

#19770 Fixed #36568 -- Confirmed support for GEOS 3.14.
  docs/ref/contrib/gis/install/geolibs.txt
Labels: geodjango

#19797 Removed unused import in docs/ref/models/expressions.txt example.
  docs/ref/models/expressions.txt
Labels: no ticket
