Repository django/django, pull requests merged in 2025-06, with the labels that each got.

#19510 Fixed #36423 -- Prevented filter_horizontal buttons from intercepting form submission.
  AUTHORS
  django/contrib/admin/static/admin/js/SelectFilter2.js
  docs/releases/5.2.2.txt
  js_tests/admin/SelectFilter2.test.js
  tests/admin_widgets/tests.py
Labels: selenium

#19506 Added validation to BaseSpatialFeatures.has_<Func>_function.
  django/contrib/gis/db/backends/base/features.py
  django/contrib/gis/db/backends/base/operations.py
  tests/gis_tests/geoapp/test_functions.py
  tests/gis_tests/tests.py
Labels: no ticket

#19550 Added follow-up to CVE-2025-48432 to security archive.
  docs/releases/security.txt
Labels: no ticket

#19262 Removed default for app_configs from system check functions.
  django/contrib/auth/checks.py
  django/contrib/contenttypes/checks.py
  django/contrib/staticfiles/checks.py
  django/core/checks/model_checks.py
Labels: no ticket

#19520 Made minor grammar and punctuation improvements in docs/topics/migrations.txt.
  docs/topics/migrations.txt
Labels: no ticket

#19560 Corrected jsonfield fieldlookup references.
  docs/topics/db/queries.txt
Labels: no ticket

#19552 Added guidance on AI-assisted security reports to docs/internals/security.txt.
  docs/internals/security.txt
Labels: no ticket

#19557 Refs #36009 -- Added GitHub action workflow to run tests with latest stable postgis version.
  .github/workflows/data/test_postgis.py.tpl
  .github/workflows/postgis.yml
Labels: geodjango

#19571 Clarified that only latest dependency versions are valid for security reports.
  docs/faq/install.txt
  docs/internals/security.txt
Labels: no ticket

#19583 Removed @skipIfDBFeature silencing of nonexistent features.
  django/test/testcases.py
  tests/test_utils/tests.py
Labels: no ticket

#19465 Fixed #36386 -- Added styles and icons for INFO and DEBUG messages in the admin.
  django/contrib/admin/static/admin/css/base.css
  django/contrib/admin/static/admin/css/dark_mode.css
  django/contrib/admin/static/admin/img/icon-debug-dark.svg
  django/contrib/admin/static/admin/img/icon-debug.svg
  django/contrib/admin/static/admin/img/icon-info-dark.svg
  django/contrib/admin/static/admin/img/icon-info.svg
  docs/releases/6.0.txt
Labels: selenium, screenshots 🖼️

#19596 Separated creating the release and setting it as default in Trac in the post-release steps.
  docs/internals/howto-release-django.txt
Labels: no ticket
