Repository django/django, pull requests merged in 2025-09, with the labels that each got.

#19789 Fixed #36578 -- Updated inline delete icon button dimensions to 24x24 pixels.
  django/contrib/admin/static/admin/css/widgets.css
Labels: selenium, screenshots 🖼️

#19854 Corrected usage of skip_file_prefixes in contributing docs.
  docs/internals/contributing/writing-code/submitting-patches.txt
Labels: no ticket

#19847 Fixed #36589 -- Handled full PartialTemplate path in assertTemplateUsed/NotUsed.
  AUTHORS
  django/test/testcases.py
  tests/test_utils/templates/template_used/partials.html
  tests/test_utils/tests.py
Labels: DjangoCon 🦄

#19878 [6.0.x] Updated source translation catalogs.
  django/conf/locale/en/LC_MESSAGES/django.po
  django/contrib/admin/locale/en/LC_MESSAGES/django.po
Labels: no ticket

#19881 Clarified feature freeze and alpha release steps in docs/internals/howto-release-django.txt.
  docs/internals/howto-release-django.txt
Labels: no ticket

#19879 Added cleanup of cache clearing to DjangoFilePrefixesTests.setUp().
  tests/deprecation/tests.py
Labels: no ticket

#19845 Fixed #36480 -- Made values() resolving error mention unselected aliases.
  django/db/models/sql/query.py
  tests/annotations/tests.py
Labels: DjangoCon 🦄

#19896 Removed Git attribute merge=union for release notes.
  .gitattributes
Labels: no ticket

#19909 Fixed assertIndexExists() crash when non-index constraint exists on the same columns.
  tests/migrations/test_base.py
Labels: no ticket

#19910 Skipped NOT NULL constraints on PostgreSQL 18+.
  django/db/backends/postgresql/introspection.py
Labels: no ticket
